name: Release

on:
  pull_request:

jobs:
  test:
    # Note that the acceptance tests do not
    # currently work on Ubuntu 22.04
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: build binaries
        env:
          CROSS: 1
          VERSION: ${{ github.ref_name }}
        run: |
          make testacc
          make build-rancher

  fossa:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # needed for the Vault authentication
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read FOSSA token
        uses: rancher-eio/read-vault-secrets@main
        with:
          secrets: |
            secret/data/github/org/rancher/fossa/push token | FOSSA_API_KEY_PUSH_ONLY

      - name: FOSSA scan
        uses: fossas/fossa-action@main
        with:
          api-key: ${{ env.FOSSA_API_KEY_PUSH_ONLY }}
          run-tests: false
