name: Pull Request

on:
  pull_request:

jobs:
  buildAndPackage:
    # Note that the acceptance tests do not
    # currently work on Ubuntu 22.04
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: build binaries
        env:
          CROSS: 1
          VERSION: ${{ github.ref_name }}
        run: |
          make build-rancher
      - name: package binaries
        run: |
          make package-rancher
